# This file is for development work. Not suitable for production.
FROM php:7.2-apache

# Use the default production configuration.
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Override with custom settings.
# COPY config/php_tt.ini $PHP_INI_DIR/conf.d/

# Install mysqli extension.
RUN docker-php-ext-install mysqli

# Install gd extension.
RUN apt-get update && apt-get install libpng-dev libfreetype6-dev -y \
 && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ \
 && docker-php-ext-install gd 

# Install ldap extension.
RUN apt-get install libldap2-dev -y \
  && docker-php-ext-install ldap
# TODO: check if ldap works, as the above is missing this step:
# && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \

# Install cron.
RUN apt-get install cron -y

# Setup cron jobs.

# Make cron logs dir
RUN mkdir -p /var/log/cron

# 1. Run at 07:15 every workday.
RUN crontab -l | { cat; echo "15 7 * * 1-5 php /var/www/html/WEB-INF/lib/cron.php >> /var/log/cron/cron.log 2>&1"; } | crontab -

# 2. Run at 15:15 every workday.
RUN crontab -l | { cat; echo "15 15 * * 1-5 php /var/www/html/WEB-INF/lib/cron.php end >> /var/log/cron/cron.log 2>&1"; } | crontab -

# Test crontabs: same as above but also run on weekends.
#RUN crontab -l | { cat; echo "20 16 * * 1-7 php /var/www/html/WEB-INF/lib/cron.php end >> /var/log/cron/cron.log 2>&1"; } | crontab -

ADD docker/cron_start.sh /docker-entrypoint.d

# Cleanup. The intention was to keep image size down.
# RUN rm -rf /var/lib/apt/lists/*
#
# The above does not work. Files are removed, but
# image files (zipped or not) are not getting smaller. Why?

# Copy application source code to /var/www/html/.
COPY . /var/www/html/
# Create configuration file.
RUN cp /var/www/html/WEB-INF/config.php.dist /var/www/html/WEB-INF/config.php
# Replace DSN value to something connectable to a Docker container running mariadb.
RUN sed -i "s|mysqli://root:no@localhost/dbname|mysqli://anuko_user:anuko_pw@anuko_db/timetracker|g" /var/www/html/WEB-INF/config.php
# Note that db is defined as anuko_db/timetracker where anuko_db is service name and timetracker is db name.
# See docker-compose.yml for details.

RUN chown -R www-data /var/www/html/
